### PR TITLE
SCAUT-983: frontend exercise

### PR DESCRIPTION
**Pull request by diablourbano**
This PR adds frontend engineering exercise, includes `mock/data.json` and `mockup` design.

### CODE REVIEW

**Review by jangnezda — APPROVED** [review]
I think it's a good exercise, maybe just slightly confusing where you first describe our stack then immediately talk about the exercise.

**Review by mikkelhartmann — COMMENTED** [review]
> Once it's done create a PR to this repo from your github account so the excercise can be reviewed.

Wont that mean that the interviewees can see each others solutions? Or can you make a PR private?

I like that they have to build a bookshelf app ❤️

**Comment by diablourbano** [comment]
> > Once it's done create a PR to this repo from your github account so the excercise can be reviewed.
> 
> Wont that mean that the interviewees can see each others solutions? Or can you make a PR private?

@mikkelhartmann that's fair point, since this repo will be public.

I'll change the instruction to the candidate to send us an invitation to her repo to review the implementation.

**Review by mikkelhartmann — APPROVED** [review]

**Review by Stephen001 — APPROVED** [review]
Pending the change to "please send us a link to the repo to review your solution"

**Pull request merged**
